"""
Delete stub textures generated by write_stub_textures_for_missing.py.

We only delete files that match the known stub signature:
  - PNG
  - 4x4 RGBA
  - strict magenta/black checkerboard

We also scope deletion to the hashes/slugs referenced by a dump, so it won't touch unrelated textures.

Usage:
  python3 webgl-gta/webgl_viewer/tools/delete_stub_textures_for_dump.py \
    --dump webgl-gta/webgl_viewer/tools/out/tex_dump_at_point_after_global_scan2.json \
    --out-dir webgl-gta/webgl_viewer/assets/models_textures \
    --regen-index
"""

from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path
from typing import Dict, Iterable, Tuple

from PIL import Image


_MODEL_TEX_RE = re.compile(r"^models_textures/(?P<hash>\d+)(?:_(?P<slug>[^/]+))?\.png$", re.IGNORECASE)


def _regen_models_textures_index(models_textures_dir: Path) -> None:
    re_hash_only = re.compile(r"^(?P<hash>\d+)\.png$", re.IGNORECASE)
    re_hash_slug = re.compile(r"^(?P<hash>\d+)_(?P<slug>[^/]+)\.png$", re.IGNORECASE)
    by_hash: Dict[str, dict] = {}

    for p in sorted(models_textures_dir.glob("*.png")):
        name = p.name
        m1 = re_hash_only.match(name)
        m2 = re_hash_slug.match(name) if not m1 else None
        if not (m1 or m2):
            continue
        h = (m1 or m2).group("hash")
        ent = by_hash.get(h)
        if ent is None:
            ent = {"hash": str(h), "hashOnly": False, "preferredFile": None, "files": []}
            by_hash[h] = ent
        ent["files"].append(name)
        if m1:
            ent["hashOnly"] = True

    for h, ent in by_hash.items():
        files = list(ent.get("files") or [])
        files.sort()
        ho = f"{h}.png"
        ent["preferredFile"] = ho if ho in files else (files[0] if files else None)

    out = {
        "schema": "webglgta-models-textures-index-v1",
        "generatedAtUnix": int(time.time()),
        "byHash": by_hash,
    }
    out_path = models_textures_dir / "index.json"
    tmp_path = models_textures_dir / "index.json.tmp"
    tmp_path.write_text(json.dumps(out, indent=2, sort_keys=True), encoding="utf-8")
    tmp_path.replace(out_path)


def _is_stub_png(path: Path) -> bool:
    try:
        with Image.open(path) as im:
            im = im.convert("RGBA")
            if im.size != (4, 4):
                return False
            px = im.load()
            mag = (255, 0, 255, 255)
            blk = (0, 0, 0, 255)
            for y in range(4):
                for x in range(4):
                    want = mag if ((x ^ y) & 1) else blk
                    if tuple(px[x, y]) != want:
                        return False
            return True
    except Exception:
        return False


def _targets_from_dump(dump_obj) -> Iterable[Tuple[str, str]]:
    rows = dump_obj.get("textures")
    if not isinstance(rows, list):
        return []
    out = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        if str(r.get("reason") or "") == "ok":
            continue
        rel = str(r.get("requestedRel") or "").strip()
        m = _MODEL_TEX_RE.match(rel)
        if not m:
            continue
        h = str(int(m.group("hash")) & 0xFFFFFFFF)
        slug = str(m.group("slug") or "").strip()
        out.append((h, slug))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dump", required=True)
    ap.add_argument("--out-dir", default="", help="defaults to webgl_viewer/assets/models_textures next to this script")
    ap.add_argument("--regen-index", action="store_true", default=False)
    args = ap.parse_args()

    dump = json.loads(Path(args.dump).read_text(encoding="utf-8", errors="ignore"))

    viewer_root = Path(__file__).resolve().parents[1]
    out_dir = Path(args.out_dir) if args.out_dir else (viewer_root / "assets" / "models_textures")
    out_dir.mkdir(parents=True, exist_ok=True)

    deleted = 0
    kept = 0
    missing = 0

    for h, slug in _targets_from_dump(dump):
        cand = [out_dir / f"{h}.png"]
        if slug:
            cand.append(out_dir / f"{h}_{slug}.png")
        for p in cand:
            if not p.exists():
                missing += 1
                continue
            if _is_stub_png(p):
                try:
                    p.unlink()
                    deleted += 1
                except Exception:
                    kept += 1
            else:
                kept += 1

    if args.regen_index:
        _regen_models_textures_index(out_dir)

    print(f"stub delete: deleted={deleted} kept={kept} missing={missing} dir={out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


