import os
import logging
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pathlib import Path
import json

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class TerrainVisualizer:
    """Class for visualizing GTA 5 terrain data"""
    
    def __init__(self, output_dir=None):
        """Initialize terrain visualizer"""
        self.output_dir = Path(output_dir) if output_dir else Path("output")
        os.makedirs(self.output_dir, exist_ok=True)
    
    def visualize_terrain(self, heightmaps, show_plot=False):
        """Visualize the extracted terrain data"""
        if not heightmaps:
            logger.error("No terrain data to visualize")
            return False
        
        for i, heightmap in enumerate(heightmaps):
            try:
                # Get terrain mesh
                X, Y, Z_max, Z_min = heightmap.get_terrain_mesh()
                
                # Create 3D plot
                fig = plt.figure(figsize=(12, 10))
                ax = fig.add_subplot(111, projection='3d')
                
                # Plot the terrain surface
                surf = ax.plot_surface(X, Y, Z_max, cmap='terrain', alpha=0.8, linewidth=0, antialiased=True)
                
                # Add colorbar
                fig.colorbar(surf, ax=ax, shrink=0.5, aspect=5)
                
                # Set labels and title
                ax.set_xlabel('X')
                ax.set_ylabel('Y')
                ax.set_zlabel('Z')
                
                # Get heightmap name
                if hasattr(heightmap, 'file_path'):
                    heightmap_name = Path(heightmap.file_path).name
                else:
                    heightmap_name = f"heightmap_{i}"
                
                ax.set_title(f'GTA 5 Terrain - {heightmap_name}')
                
                # Save the plot
                output_file = self.output_dir / f"terrain_map_{i}.png"
                plt.savefig(output_file, dpi=300, bbox_inches='tight')
                logger.info(f"Saved terrain visualization to {output_file}")
                
                # Show the plot if requested
                if show_plot:
                    plt.show()
                else:
                    plt.close(fig)
            except Exception as e:
                logger.error(f"Error visualizing terrain: {e}")
                import traceback
                logger.debug(traceback.format_exc())
        
        return True


class TerrainExporter:
    """Class for exporting GTA 5 terrain data"""
    
    def __init__(self, output_dir=None):
        """Initialize terrain exporter"""
        self.output_dir = Path(output_dir) if output_dir else Path("output")
        os.makedirs(self.output_dir, exist_ok=True)
    
    def export_terrain_obj(self, heightmaps):
        """Export terrain as OBJ file for 3D modeling software"""
        if not heightmaps:
            logger.error("No terrain data to export")
            return False
        
        for i, heightmap in enumerate(heightmaps):
            try:
                # Get terrain mesh
                X, Y, Z_max, _ = heightmap.get_terrain_mesh()
                
                # Get heightmap dimensions
                if hasattr(heightmap, 'width') and hasattr(heightmap, 'height'):
                    width = heightmap.width
                    height = heightmap.height
                else:
                    width = X.shape[1]
                    height = X.shape[0]
                
                # Get heightmap name
                if hasattr(heightmap, 'file_path'):
                    heightmap_name = Path(heightmap.file_path).name
                else:
                    heightmap_name = f"heightmap_{i}"
                
                # Prepare OBJ file
                output_file = self.output_dir / f"terrain_{i}.obj"
                
                with open(output_file, 'w') as f:
                    # Write OBJ header
                    f.write(f"# GTA 5 Terrain - {heightmap_name}\n")
                    f.write(f"# Generated by GTA5 Terrain Extractor\n")
                    f.write(f"# Dimensions: {width}x{height}\n\n")
                    
                    # Write vertices
                    vertex_count = 0
                    for y in range(height):
                        for x in range(width):
                            f.write(f"v {X[y, x]} {Y[y, x]} {Z_max[y, x]}\n")
                            vertex_count += 1
                    
                    f.write("\n")
                    
                    # Write faces (triangles)
                    for y in range(height - 1):
                        for x in range(width - 1):
                            # Calculate vertex indices (OBJ indices start at 1)
                            v1 = y * width + x + 1
                            v2 = y * width + (x + 1) + 1
                            v3 = (y + 1) * width + x + 1
                            v4 = (y + 1) * width + (x + 1) + 1
                            
                            # Write two triangles for each grid cell
                            f.write(f"f {v1} {v2} {v3}\n")
                            f.write(f"f {v3} {v2} {v4}\n")
                
                logger.info(f"Exported terrain to OBJ file: {output_file}")
            except Exception as e:
                logger.error(f"Error exporting terrain to OBJ: {e}")
                import traceback
                logger.debug(traceback.format_exc())
        
        return True
    
    def export_terrain_data(self, heightmaps, formats=None):
        """Export terrain data in various formats for further processing"""
        if not heightmaps:
            logger.error("No terrain data to export")
            return False
        
        if formats is None:
            formats = ['numpy', 'csv', 'json']
        elif isinstance(formats, str):
            formats = [formats]
        
        for i, heightmap in enumerate(heightmaps):
            try:
                # Get terrain mesh
                X, Y, Z_max, Z_min = heightmap.get_terrain_mesh()
                
                # Get heightmap dimensions
                if hasattr(heightmap, 'width') and hasattr(heightmap, 'height'):
                    width = heightmap.width
                    height = heightmap.height
                    bb_min = heightmap.bb_min
                    bb_max = heightmap.bb_max
                else:
                    width = X.shape[1]
                    height = X.shape[0]
                    bb_min = (X.min(), Y.min(), Z_min.min())
                    bb_max = (X.max(), Y.max(), Z_max.max())
                
                # Get heightmap name
                if hasattr(heightmap, 'file_path'):
                    heightmap_name = Path(heightmap.file_path).name
                else:
                    heightmap_name = f"heightmap_{i}"
                
                if 'numpy' in formats:
                    # Save as NumPy arrays
                    output_file = self.output_dir / f"terrain_data_{i}.npz"
                    np.savez(
                        output_file,
                        X=X,
                        Y=Y,
                        Z_max=Z_max,
                        Z_min=Z_min,
                        width=width,
                        height=height,
                        bb_min=bb_min,
                        bb_max=bb_max,
                        name=heightmap_name
                    )
                    logger.info(f"Exported terrain data to NumPy file: {output_file}")
                
                if 'csv' in formats:
                    # Save as CSV files
                    output_file = self.output_dir / f"terrain_data_{i}.csv"
                    with open(output_file, 'w') as f:
                        f.write("x,y,z_max,z_min\n")
                        for y in range(height):
                            for x in range(width):
                                f.write(f"{X[y, x]},{Y[y, x]},{Z_max[y, x]},{Z_min[y, x]}\n")
                    logger.info(f"Exported terrain data to CSV file: {output_file}")
                
                if 'json' in formats:
                    # Save as JSON file
                    output_file = self.output_dir / f"terrain_data_{i}.json"
                    data = {
                        "name": heightmap_name,
                        "width": int(width),
                        "height": int(height),
                        "bb_min": [float(v) for v in bb_min],
                        "bb_max": [float(v) for v in bb_max],
                        "x": X.tolist(),
                        "y": Y.tolist(),
                        "z_max": Z_max.tolist(),
                        "z_min": Z_min.tolist()
                    }
                    with open(output_file, 'w') as f:
                        json.dump(data, f)
                    logger.info(f"Exported terrain data to JSON file: {output_file}")
            
            except Exception as e:
                logger.error(f"Error exporting terrain data: {e}")
                import traceback
                logger.debug(traceback.format_exc())
        
        return True 