#!/usr/bin/env python3
"""
Generate a movement-related asset index from GTA5 RPF archives using CodeWalker (via pythonnet).

This is the closest “strict GTA5 client + CodeWalker” analogue to “movement packets / sync tree nodes”:
- We can't extract Rockstar's internal net sync node schemas or raw input->movement code from CodeWalker alone.
- We *can* enumerate the concrete assets the game uses for locomotion: clipsets, anim dictionaries/clips,
  ped movement-related meta files, etc., and then map user inputs to those assets at the gameplay layer.

Output: `docs/generated/movement-asset-index.md` by default.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path


MOVEMENT_KEYWORDS = (
    "clip",
    "clipset",
    "move",
    "movement",
    "locomotion",
    "walk",
    "run",
    "jog",
    "sprint",
    "strafe",
    "crouch",
    "stealth",
    "jump",
    "vault",
    "roll",
    "ragdoll",
    "swim",
    "drive",
    "aim",
    "cover",
    "ped",
    "player",
)

# File types that are commonly involved in locomotion/animation/ped behaviour.
INTERESTING_EXTS = (
    ".ycd",  # animation clip dictionary
    ".ymt",  # meta (various)
    ".meta",  # meta (xml-ish in some contexts)
    ".ytyp",  # archetypes (not strictly movement but can reference peds)
    ".ybn",  # collisions (not movement, but sometimes wanted for character controller context)
)


def is_interesting(name: str) -> bool:
    low = name.lower()
    if not any(low.endswith(ext) for ext in INTERESTING_EXTS):
        return False
    return any(k in low for k in MOVEMENT_KEYWORDS)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--gta5-path",
        default=os.environ.get("gta5_path") or os.environ.get("GTA5_PATH") or "",
        help="Path to GTA5 install folder (should contain GTA5.exe, common.rpf, update/...).",
    )
    ap.add_argument(
        "--out",
        default="docs/generated/movement-asset-index.md",
        help="Output markdown path (relative to repo root unless absolute).",
    )
    ap.add_argument(
        "--max",
        type=int,
        default=2000,
        help="Max number of matching entries to include (to keep output reasonable).",
    )
    args = ap.parse_args()

    repo_root = Path(os.getcwd()).resolve()
    # Ensure imports work when running as `python3 scripts/...` (repo is not a package install).
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    gta5_path = Path(args.gta5_path).expanduser().resolve() if args.gta5_path else Path()
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = (repo_root / out_path).resolve()

    if not gta5_path.exists():
        raise SystemExit(
            "--gta5-path is required (or set env gta5_path). "
            "Example: --gta5-path /data/webglgta/webgl-gta/gtav"
        )

    # Lazy import: this requires pythonnet + our CodeWalker integration.
    from gta5_modules.dll_manager import DllManager

    dm = DllManager(str(gta5_path))
    if not dm.initialized:
        raise SystemExit("DllManager failed to initialize (see logs above).")

    rm = dm.get_rpf_manager()

    matches: list[str] = []
    # This scan can take a bit; CodeWalker has already indexed entries during Init().
    for rpf in rm.AllRpfs:
        entries = getattr(rpf, "AllEntries", None)
        if not entries:
            continue
        for e in entries:
            name = str(e.Name)
            if is_interesting(name):
                matches.append(str(e.Path))
                if len(matches) >= args.max:
                    break
        if len(matches) >= args.max:
            break

    # Group a little for readability
    grouped: dict[str, list[str]] = defaultdict(list)
    for p in matches:
        low = p.lower()
        ext = Path(low).suffix
        grouped[ext].append(p)

    lines: list[str] = []
    lines.append("# Generated: Movement-related GTA5 assets (CodeWalker index scan)")
    lines.append("")
    lines.append("This report is generated by `scripts/generate_movement_asset_index.py`.")
    lines.append("")
    lines.append("## What this helps with")
    lines.append("")
    lines.append("- **Helps**: finding the actual clipsets/animation dictionaries/meta files that back locomotion.")
    lines.append("- **Does not directly give**: Rockstar's internal net sync-node schema or raw input→movement code.")
    lines.append("")
    lines.append("## Inputs mapping approach (practical)")
    lines.append("")
    lines.append("To map user inputs, you typically:")
    lines.append("1. Identify locomotion clipsets/anim dicts used in each state (walk/run/sprint/crouch/strafe).")
    lines.append("2. Cross-reference those names with known control actions and state machines (your client code).")
    lines.append("3. (Optional) Add runtime logging in your client to print active clipset/anim per frame while pressing keys.")
    lines.append("")
    lines.append("## Scan parameters")
    lines.append("")
    lines.append(f"- **GTA5 path**: `{gta5_path}`")
    lines.append(f"- **Max entries**: `{args.max}`")
    lines.append("")
    lines.append(f"## Matches ({len(matches)})")
    lines.append("")

    for ext in sorted(grouped.keys()):
        lines.append(f"### `{ext}`")
        lines.append("")
        for p in grouped[ext]:
            lines.append(f"- `{p}`")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote: {out_path} ({len(lines)} lines, {len(matches)} matches)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


